-- P0-05 / SEC-003 with action-scoped SEC-010 enforcement.
-- Generated by Supabase CLI 2.113.0 as 20260813163013_sec003_moderator_admin_boundary.sql.
-- This is a forward-only, no-data migration over the verified baseline chain.

begin;

create or replace function private.require_current_moderator()
returns uuid
language plpgsql
stable
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := auth.uid();
begin
  if actor is null or not exists (
    select 1 from public.moderators where user_id = actor
  ) then
    raise exception using errcode = '42501', message = 'Current moderator membership is required';
  end if;
  return actor;
end;
$$;
revoke all on function private.require_current_moderator() from public, anon, authenticated;

create or replace function private.require_current_admin_aal2()
returns uuid
language plpgsql
stable
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := auth.uid();
begin
  if actor is null or not exists (
    select 1 from public.moderators where user_id = actor and role = 'admin'
  ) then
    raise exception using errcode = '42501', message = 'Current administrator membership is required';
  end if;
  if coalesce(auth.jwt() ->> 'aal', '') <> 'aal2' then
    raise exception using errcode = '42501', message = 'AAL2 is required for this administrator action';
  end if;
  return actor;
end;
$$;
revoke all on function private.require_current_admin_aal2() from public, anon, authenticated;

create or replace function private.append_privileged_audit(
  p_actor uuid,
  p_entity_type text,
  p_entity_id uuid,
  p_action text,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  if p_actor is null or p_entity_type is null or p_action is null then
    raise exception using errcode = '22023', message = 'Audit identity and action are required';
  end if;
  insert into public.audit_log(actor_id, entity_type, entity_id, action, details)
  values (p_actor, p_entity_type, p_entity_id, p_action, coalesce(p_details, '{}'::jsonb));
end;
$$;
revoke all on function private.append_privileged_audit(uuid, text, uuid, text, jsonb)
  from public, anon, authenticated;

-- Direct privileged DML is denied. Named functions below are the only client
-- mutation boundary. Review/complaint INSERT is intentionally left untouched
-- because SEC-004 is a separate finding.
revoke insert, update, delete on table public.specialists from public, anon, authenticated;
revoke insert, update, delete on table public.verifications from public, anon, authenticated;
revoke update, delete on table public.reviews from public, anon, authenticated;
revoke update, delete on table public.complaints from public, anon, authenticated;
revoke insert, update, delete on table public.moderators from public, anon, authenticated;
revoke insert, update, delete on table public.categories from public, anon, authenticated;
revoke update on table public.site_content from public, anon, authenticated;
revoke insert, update, delete on table public.trust_badges from public, anon, authenticated;
revoke insert, update, delete on table public.specialist_trust_badges from public, anon, authenticated;
revoke insert, update, delete on table public.audit_log from public, anon, authenticated;

drop policy if exists "Moderator updates applications" on public.applications;
drop policy if exists "Moderators update specialists" on public.specialists;
drop policy if exists "Moderators manage verifications" on public.verifications;
drop policy if exists "Moderator updates reviews" on public.reviews;
drop policy if exists "Moderator updates complaints" on public.complaints;
drop policy if exists "Admin manages categories" on public.categories;
drop policy if exists "Admin manages moderators" on public.moderators;
drop policy if exists "Admins update site content" on public.site_content;
drop policy if exists "Admins manage trust badges" on public.trust_badges;
drop policy if exists "Admins manage specialist badges" on public.specialist_trust_badges;
drop policy if exists "Moderator writes audit" on public.audit_log;
drop policy if exists "Moderators write own audit entries" on public.audit_log;

create or replace function public.moderator_decide_application(
  p_application_id uuid,
  p_expected_updated_at timestamptz,
  p_decision text,
  p_internal_note text default null,
  p_applicant_message text default null
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_moderator();
  current_row public.applications;
  target_status public.application_status;
begin
  if p_decision not in ('request_changes', 'reject') then
    raise exception using errcode = '22023', message = 'Unsupported application decision';
  end if;
  if p_decision = 'request_changes' and coalesce(length(trim(p_applicant_message)), 0) = 0 then
    raise exception using errcode = '22023', message = 'Applicant message is required';
  end if;
  if length(coalesce(p_internal_note, '')) > 5000 or length(coalesce(p_applicant_message, '')) > 5000 then
    raise exception using errcode = '22023', message = 'Moderation text is too long';
  end if;

  select * into current_row from public.applications
  where id = p_application_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Application not found'; end if;
  if p_expected_updated_at is null or current_row.updated_at is distinct from p_expected_updated_at then
    raise exception using errcode = '40001', message = 'Application changed after review';
  end if;
  if current_row.status not in ('new','screening','info_required','changes_requested','call_required','call_scheduled') then
    raise exception using errcode = '22023', message = 'Application transition is not allowed';
  end if;

  target_status := case when p_decision = 'request_changes' then 'changes_requested'::public.application_status else 'rejected'::public.application_status end;
  update public.applications
  set status = target_status,
      internal_notes = nullif(trim(p_internal_note), ''),
      applicant_message = case when target_status = 'changes_requested' then trim(p_applicant_message) else null end
  where id = current_row.id;

  perform private.append_privileged_audit(
    actor, 'application', current_row.id,
    case when target_status = 'changes_requested' then 'changes_requested' else 'rejected' end,
    jsonb_build_object('before_status', current_row.status, 'after_status', target_status)
  );
end;
$$;
revoke all on function public.moderator_decide_application(uuid, timestamptz, text, text, text)
  from public, anon, authenticated;
grant execute on function public.moderator_decide_application(uuid, timestamptz, text, text, text)
  to authenticated;

create or replace function public.request_specialist_revision_changes(revision_uuid uuid, note text)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_moderator();
  current_row public.specialist_revisions;
begin
  if coalesce(length(trim(note)), 0) = 0 or length(note) > 5000 then
    raise exception using errcode = '22023', message = 'A valid comment is required';
  end if;
  select * into current_row from public.specialist_revisions
  where id = revision_uuid for update;
  if not found or current_row.status <> 'pending' then
    raise exception using errcode = '22023', message = 'Revision is not pending';
  end if;
  update public.specialist_revisions
  set status = 'changes_requested', moderator_id = actor,
      moderator_comment = trim(note), decided_at = clock_timestamp()
  where id = current_row.id;
  perform private.append_privileged_audit(
    actor, 'specialist_revision', current_row.id, 'changes_requested',
    jsonb_build_object('before_status', current_row.status, 'after_status', 'changes_requested')
  );
end;
$$;
revoke all on function public.request_specialist_revision_changes(uuid, text)
  from public, anon, authenticated;
grant execute on function public.request_specialist_revision_changes(uuid, text)
  to authenticated;

create or replace function public.apply_specialist_revision(
  revision_uuid uuid,
  approve boolean,
  note text default null
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_moderator();
  current_row public.specialist_revisions;
  payload jsonb;
  offers jsonb;
  legacy_services text[];
  current_profile public.specialists;
begin
  if not approve and (coalesce(length(trim(note)), 0) = 0 or length(note) > 5000) then
    raise exception using errcode = '22023', message = 'A valid rejection comment is required';
  end if;
  select * into current_row from public.specialist_revisions
  where id = revision_uuid for update;
  if not found then raise exception using errcode = 'P0002', message = 'Revision not found'; end if;
  if current_row.status <> 'pending' then
    raise exception using errcode = '22023', message = 'Revision has already been decided';
  end if;
  select * into current_profile from public.specialists
  where id = current_row.specialist_id and owner_id = current_row.owner_id for update;
  if not found then raise exception using errcode = '22023', message = 'Revision owner mismatch'; end if;
  payload := current_row.payload;

  if approve and (
    nullif(payload->>'avatar_path','') is distinct from current_profile.avatar_path
    or (payload ? 'gallery_paths' and array(select jsonb_array_elements_text(coalesce(payload->'gallery_paths','[]'::jsonb))) is distinct from current_profile.gallery_paths)
  ) then
    raise exception using errcode = '22023', message = 'Canonical server publication required for changed media';
  end if;

  if approve and payload->>'contract_version' = '2' then
    offers := payload->'work_offers';
    legacy_services := public.work_offer_titles(offers);
    update public.specialists set
      contract_version = 2,
      full_name = coalesce(nullif(payload->>'full_name',''), full_name),
      country = coalesce(nullif(payload->>'country',''), country),
      city = coalesce(nullif(payload->>'city',''), city),
      category_id = case when nullif(payload->>'category_id','') is null then category_id else (payload->>'category_id')::uuid end,
      additional_category_ids = coalesce(array(select jsonb_array_elements_text(coalesce(payload->'additional_category_ids','[]'::jsonb))::uuid), '{}'::uuid[]),
      specialization = nullif(payload->>'specialization',''),
      experience_years = (payload->>'experience_years')::integer,
      profile_summary = payload->>'profile_summary',
      short_description = payload->>'profile_summary',
      full_description = payload->>'full_description',
      help_topics = payload->'help_topics',
      work_offers = offers,
      services = legacy_services,
      service_mode = public.work_offer_mode(offers, service_mode),
      avatar_path = payload->>'avatar_path',
      status = 'published',
      published_at = coalesce(published_at, clock_timestamp()),
      updated_at = clock_timestamp()
    where id = current_row.specialist_id and owner_id = current_row.owner_id;
  elsif approve then
    update public.specialists set
      full_name = coalesce(nullif(payload->>'full_name',''), full_name),
      country = coalesce(nullif(payload->>'country',''), country),
      city = coalesce(nullif(payload->>'city',''), city),
      service_mode = coalesce(nullif(payload->>'service_mode',''), service_mode),
      category_id = case when nullif(payload->>'category_id','') is null then category_id else (payload->>'category_id')::uuid end,
      additional_category_ids = coalesce(array(select jsonb_array_elements_text(coalesce(payload->'additional_category_ids', to_jsonb(additional_category_ids)))::uuid), additional_category_ids),
      specialization = coalesce(nullif(payload->>'specialization',''), specialization),
      experience_years = case when nullif(payload->>'experience_years','') is null then experience_years else (payload->>'experience_years')::integer end,
      services = coalesce(array(select jsonb_array_elements_text(coalesce(payload->'services', to_jsonb(services)))), services),
      profile_summary = coalesce(nullif(payload->>'profile_summary',''), nullif(payload->>'short_description',''), profile_summary),
      short_description = coalesce(nullif(payload->>'short_description',''), short_description),
      full_description = coalesce(nullif(payload->>'full_description',''), full_description),
      help_topics = coalesce(payload->'help_topics', help_topics),
      work_offers = coalesce(payload->'work_offers', work_offers),
      public_contact = coalesce(nullif(payload->>'public_contact',''), public_contact),
      portfolio_links = coalesce(array(select jsonb_array_elements_text(coalesce(payload->'portfolio_links', to_jsonb(portfolio_links)))), portfolio_links),
      video_links = coalesce(array(select jsonb_array_elements_text(coalesce(payload->'video_links', to_jsonb(video_links)))), video_links),
      avatar_path = coalesce(nullif(payload->>'avatar_path',''), avatar_path),
      gallery_paths = coalesce(array(select jsonb_array_elements_text(coalesce(payload->'gallery_paths', to_jsonb(gallery_paths)))), gallery_paths),
      recommendations = coalesce(nullif(payload->>'recommendations',''), recommendations),
      status = 'published',
      published_at = coalesce(published_at, clock_timestamp()),
      updated_at = clock_timestamp()
    where id = current_row.specialist_id and owner_id = current_row.owner_id;
  end if;

  update public.specialist_revisions
  set status = case when approve then 'approved' else 'rejected' end,
      moderator_id = actor,
      moderator_comment = nullif(trim(note), ''),
      decided_at = clock_timestamp()
  where id = current_row.id;
  perform private.append_privileged_audit(
    actor, 'specialist_revision', current_row.id,
    case when approve then 'approved' else 'rejected' end,
    jsonb_build_object('before_status', current_row.status, 'after_status', case when approve then 'approved' else 'rejected' end)
  );
end;
$$;
revoke all on function public.apply_specialist_revision(uuid, boolean, text)
  from public, anon, authenticated;
grant execute on function public.apply_specialist_revision(uuid, boolean, text)
  to authenticated;

create or replace function public.moderate_review(p_review_id uuid, p_publish boolean)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_moderator();
  current_row public.reviews;
begin
  select * into current_row from public.reviews where id = p_review_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Review not found'; end if;
  if current_row.evidence_checked and current_row.is_published is not distinct from p_publish then
    raise exception using errcode = '22023', message = 'Review decision has already been applied';
  end if;
  update public.reviews set is_published = p_publish, evidence_checked = true
  where id = current_row.id;
  perform private.append_privileged_audit(
    actor, 'review', current_row.id,
    case when p_publish then 'approved' else 'dismissed' end,
    jsonb_build_object('published', p_publish)
  );
end;
$$;
revoke all on function public.moderate_review(uuid, boolean) from public, anon, authenticated;
grant execute on function public.moderate_review(uuid, boolean) to authenticated;

create or replace function public.moderate_complaint(p_complaint_id uuid, p_target_status public.complaint_status)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_moderator();
  current_row public.complaints;
begin
  if p_target_status not in ('resolved','dismissed') then
    raise exception using errcode = '22023', message = 'Unsupported complaint decision';
  end if;
  select * into current_row from public.complaints where id = p_complaint_id for update;
  if not found or current_row.status not in ('new','reviewing') then
    raise exception using errcode = '22023', message = 'Complaint transition is not allowed';
  end if;
  update public.complaints set status = p_target_status where id = current_row.id;
  perform private.append_privileged_audit(
    actor, 'complaint', current_row.id,
    case when p_target_status = 'resolved' then 'approved' else 'dismissed' end,
    jsonb_build_object('before_status', current_row.status, 'after_status', p_target_status)
  );
end;
$$;
revoke all on function public.moderate_complaint(uuid, public.complaint_status)
  from public, anon, authenticated;
grant execute on function public.moderate_complaint(uuid, public.complaint_status)
  to authenticated;

create or replace function public.admin_transition_application(
  p_application_id uuid,
  p_expected_status public.application_status,
  p_target_status public.application_status
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
  current_row public.applications;
begin
  select * into current_row from public.applications where id = p_application_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Application not found'; end if;
  if current_row.status is distinct from p_expected_status then
    raise exception using errcode = '40001', message = 'Application state is stale';
  end if;
  if not (
    p_target_status = 'withdrawn' and current_row.status in ('new','screening','info_required','changes_requested','call_required','call_scheduled','rejected')
    or p_target_status = 'new' and current_row.status = 'withdrawn'
  ) then
    raise exception using errcode = '22023', message = 'Admin application transition is not allowed';
  end if;
  update public.applications set status = p_target_status where id = current_row.id;
  perform private.append_privileged_audit(
    actor, 'application', current_row.id,
    case when p_target_status = 'withdrawn' then 'archived' else 'restored_from_archive' end,
    jsonb_build_object('before_status', current_row.status, 'after_status', p_target_status)
  );
end;
$$;
revoke all on function public.admin_transition_application(uuid, public.application_status, public.application_status)
  from public, anon, authenticated;
grant execute on function public.admin_transition_application(uuid, public.application_status, public.application_status)
  to authenticated;

create or replace function public.admin_delete_application(p_application_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
  current_row public.applications;
begin
  select * into current_row from public.applications where id = p_application_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Application not found'; end if;
  delete from public.applications where id = current_row.id;
  perform private.append_privileged_audit(actor, 'application', current_row.id, 'permanently_deleted', jsonb_build_object('before_status', current_row.status));
end;
$$;
revoke all on function public.admin_delete_application(uuid) from public, anon, authenticated;
grant execute on function public.admin_delete_application(uuid) to authenticated;

create or replace function public.admin_delete_revision(p_revision_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
  current_row public.specialist_revisions;
begin
  select * into current_row from public.specialist_revisions where id = p_revision_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Revision not found'; end if;
  delete from public.specialist_revisions where id = current_row.id;
  perform private.append_privileged_audit(actor, 'specialist_revision', current_row.id, 'permanently_deleted', jsonb_build_object('before_status', current_row.status));
end;
$$;
revoke all on function public.admin_delete_revision(uuid) from public, anon, authenticated;
grant execute on function public.admin_delete_revision(uuid) to authenticated;

create or replace function private.assert_admin_profile_transition(
  p_before public.profile_status,
  p_after public.profile_status
)
returns void
language plpgsql
immutable
set search_path = pg_catalog
as $$
begin
  if p_before is not distinct from p_after then return; end if;
  if not (
    (p_before = 'published' and p_after in ('suspended','blocked','archived'))
    or (p_before = 'suspended' and p_after in ('published','blocked','archived'))
    or (p_before = 'blocked' and p_after in ('published','archived'))
    or (p_before = 'archived' and p_after = 'published')
  ) then
    raise exception using errcode = '22023', message = 'Admin profile transition is not allowed';
  end if;
end;
$$;
revoke all on function private.assert_admin_profile_transition(public.profile_status, public.profile_status)
  from public, anon, authenticated;

create or replace function public.admin_update_specialist_controls(
  p_specialist_id uuid,
  p_expected_status public.profile_status,
  p_target_status public.profile_status,
  p_identity_checked boolean,
  p_education_checked boolean,
  p_experience_checked boolean,
  p_qualifications_checked boolean,
  p_references_checked boolean,
  p_sources_checked integer
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
  current_row public.specialists;
begin
  if p_sources_checked is null or p_sources_checked not between 0 and 999
     or p_identity_checked is null or p_education_checked is null
     or p_experience_checked is null or p_qualifications_checked is null
     or p_references_checked is null then
    raise exception using errcode = '22023', message = 'Verification facts are invalid';
  end if;
  select * into current_row from public.specialists where id = p_specialist_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Specialist not found'; end if;
  if current_row.status is distinct from p_expected_status then
    raise exception using errcode = '40001', message = 'Specialist state is stale';
  end if;
  perform private.assert_admin_profile_transition(current_row.status, p_target_status);

  update public.specialists
  set status = p_target_status,
      published_at = case when p_target_status = 'published' then coalesce(published_at, clock_timestamp()) else published_at end
  where id = current_row.id;

  insert into public.verifications(
    specialist_id, identity_checked, education_checked, experience_checked,
    qualifications_checked, references_checked, sources_checked, checked_by, checked_at
  ) values (
    current_row.id, p_identity_checked, p_education_checked, p_experience_checked,
    p_qualifications_checked, p_references_checked, p_sources_checked, actor, clock_timestamp()
  )
  on conflict (specialist_id) do update set
    identity_checked = excluded.identity_checked,
    education_checked = excluded.education_checked,
    experience_checked = excluded.experience_checked,
    qualifications_checked = excluded.qualifications_checked,
    references_checked = excluded.references_checked,
    sources_checked = excluded.sources_checked,
    checked_by = excluded.checked_by,
    checked_at = excluded.checked_at;

  perform private.append_privileged_audit(
    actor, 'specialist', current_row.id, 'profile_and_verification_updated',
    jsonb_build_object('before_status', current_row.status, 'after_status', p_target_status, 'sources_checked', p_sources_checked)
  );
end;
$$;
revoke all on function public.admin_update_specialist_controls(uuid, public.profile_status, public.profile_status, boolean, boolean, boolean, boolean, boolean, integer)
  from public, anon, authenticated;
grant execute on function public.admin_update_specialist_controls(uuid, public.profile_status, public.profile_status, boolean, boolean, boolean, boolean, boolean, integer)
  to authenticated;

create or replace function public.admin_transition_specialist(
  p_specialist_id uuid,
  p_expected_status public.profile_status,
  p_target_status public.profile_status
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
  current_row public.specialists;
begin
  select * into current_row from public.specialists where id = p_specialist_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Specialist not found'; end if;
  if current_row.status is distinct from p_expected_status then
    raise exception using errcode = '40001', message = 'Specialist state is stale';
  end if;
  perform private.assert_admin_profile_transition(current_row.status, p_target_status);
  update public.specialists
  set status = p_target_status,
      published_at = case when p_target_status = 'published' then coalesce(published_at, clock_timestamp()) else published_at end
  where id = current_row.id;
  perform private.append_privileged_audit(
    actor, 'specialist', current_row.id,
    case when p_target_status = 'published' then 'restored_to_public' else 'archived_from_public' end,
    jsonb_build_object('before_status', current_row.status, 'after_status', p_target_status)
  );
end;
$$;
revoke all on function public.admin_transition_specialist(uuid, public.profile_status, public.profile_status)
  from public, anon, authenticated;
grant execute on function public.admin_transition_specialist(uuid, public.profile_status, public.profile_status)
  to authenticated;

create or replace function public.admin_set_manual_trust_badges(p_specialist_id uuid, p_badge_ids uuid[])
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
  selected uuid[] := coalesce(p_badge_ids, '{}'::uuid[]);
begin
  perform 1 from public.specialists where id = p_specialist_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Specialist not found'; end if;
  if cardinality(selected) > 50 or cardinality(selected) <> (select count(distinct value) from unnest(selected) value) then
    raise exception using errcode = '22023', message = 'Badge selection is invalid';
  end if;
  if exists (
    select 1 from unnest(selected) value
    left join public.trust_badges badge on badge.id = value
    where badge.id is null or badge.assignment_type <> 'manual' or not badge.is_active
  ) then
    raise exception using errcode = '22023', message = 'Badge selection contains a disallowed badge';
  end if;
  delete from public.specialist_trust_badges
  where specialist_id = p_specialist_id and source = 'manual' and not (badge_id = any(selected));
  insert into public.specialist_trust_badges(specialist_id, badge_id, assigned_by, source, admin_note)
  select p_specialist_id, value, actor, 'manual', null from unnest(selected) value
  on conflict (specialist_id, badge_id) do nothing;
  perform private.append_privileged_audit(
    actor, 'specialist', p_specialist_id, 'trust_badges_updated',
    jsonb_build_object('manual_badge_count', cardinality(selected))
  );
end;
$$;
revoke all on function public.admin_set_manual_trust_badges(uuid, uuid[])
  from public, anon, authenticated;
grant execute on function public.admin_set_manual_trust_badges(uuid, uuid[])
  to authenticated;

create or replace function public.admin_update_site_content(p_content jsonb)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
  allowed_keys text[] := array[
    'brand_name','tagline','hero_title','hero_text','contact_email','about_text',
    'rules_intro','privacy_text','seo_title','seo_description'
  ];
begin
  if jsonb_typeof(p_content) is distinct from 'object'
     or not (p_content ?& allowed_keys)
     or exists (select 1 from jsonb_object_keys(p_content) key where not (key = any(allowed_keys))) then
    raise exception using errcode = '22023', message = 'Site content payload has unsupported fields';
  end if;
  update public.site_content set
    brand_name = p_content->>'brand_name', tagline = p_content->>'tagline',
    hero_title = p_content->>'hero_title', hero_text = p_content->>'hero_text',
    contact_email = p_content->>'contact_email', about_text = p_content->>'about_text',
    rules_intro = p_content->>'rules_intro', privacy_text = p_content->>'privacy_text',
    seo_title = p_content->>'seo_title', seo_description = p_content->>'seo_description',
    updated_by = actor
  where id = true;
  if not found then raise exception using errcode = 'P0002', message = 'Site content row not found'; end if;
  perform private.append_privileged_audit(actor, 'site_content', null, 'updated', jsonb_build_object('field_count', cardinality(allowed_keys)));
end;
$$;
revoke all on function public.admin_update_site_content(jsonb) from public, anon, authenticated;
grant execute on function public.admin_update_site_content(jsonb) to authenticated;

create or replace function public.admin_set_moderator_role(p_user_id uuid, p_role public.moderator_role default null)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
  previous_role public.moderator_role;
begin
  if p_user_id is null or p_user_id = actor then
    raise exception using errcode = '22023', message = 'Administrators cannot change their own role';
  end if;
  select role into previous_role from public.moderators where user_id = p_user_id for update;
  if p_role is null then
    delete from public.moderators where user_id = p_user_id;
  else
    insert into public.moderators(user_id, role) values (p_user_id, p_role)
    on conflict (user_id) do update set role = excluded.role;
  end if;
  perform private.append_privileged_audit(
    actor, 'moderator_membership', p_user_id, 'role_changed',
    jsonb_build_object('before_role', previous_role, 'after_role', p_role)
  );
end;
$$;
revoke all on function public.admin_set_moderator_role(uuid, public.moderator_role)
  from public, anon, authenticated;
grant execute on function public.admin_set_moderator_role(uuid, public.moderator_role)
  to authenticated;

create or replace function public.admin_upsert_category(
  p_category_id uuid,
  p_name text,
  p_slug text,
  p_group_name text,
  p_is_active boolean
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
begin
  if p_category_id is null or coalesce(length(trim(p_name)),0) < 2
     or p_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' or p_is_active is null then
    raise exception using errcode = '22023', message = 'Category payload is invalid';
  end if;
  insert into public.categories(id, name, slug, group_name, is_active)
  values (p_category_id, trim(p_name), p_slug, nullif(trim(p_group_name),''), p_is_active)
  on conflict (id) do update set
    name = excluded.name, slug = excluded.slug,
    group_name = excluded.group_name, is_active = excluded.is_active;
  perform private.append_privileged_audit(actor, 'category', p_category_id, 'upserted', jsonb_build_object('is_active', p_is_active));
end;
$$;
revoke all on function public.admin_upsert_category(uuid, text, text, text, boolean)
  from public, anon, authenticated;
grant execute on function public.admin_upsert_category(uuid, text, text, text, boolean)
  to authenticated;

create or replace function public.admin_delete_category(p_category_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
begin
  perform 1 from public.categories where id = p_category_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'Category not found'; end if;
  delete from public.categories where id = p_category_id;
  perform private.append_privileged_audit(actor, 'category', p_category_id, 'deleted', '{}'::jsonb);
end;
$$;
revoke all on function public.admin_delete_category(uuid) from public, anon, authenticated;
grant execute on function public.admin_delete_category(uuid) to authenticated;

create or replace function public.admin_retry_email_notification(p_notification_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  actor uuid := private.require_current_admin_aal2();
  current_status text;
begin
  select status into current_status from public.email_notifications
  where id = p_notification_id for update;
  if not found or current_status not in ('failed','cancelled') then
    raise exception using errcode = '22023', message = 'Notification is not retryable';
  end if;
  update public.email_notifications
  set status = 'pending', next_attempt_at = clock_timestamp(), last_error = null
  where id = p_notification_id;
  perform private.append_privileged_audit(actor, 'email_notification', p_notification_id, 'retry_requested', jsonb_build_object('before_status', current_status));
end;
$$;
revoke all on function public.admin_retry_email_notification(uuid)
  from public, anon, authenticated;
grant execute on function public.admin_retry_email_notification(uuid)
  to authenticated;

-- Wrap the existing SEC-001 service-only publication primitives so the
-- privileged actor and decision audit are committed in the same transaction.
create or replace function public.approve_application_with_canonical_media_v2(
  application_uuid uuid,
  reviewer_uuid uuid,
  expected_updated_at timestamptz,
  note text,
  avatar_descriptor jsonb,
  gallery_descriptors jsonb
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  if reviewer_uuid is null or not exists (
    select 1 from public.moderators where user_id = reviewer_uuid
  ) then
    raise exception using errcode = '42501', message = 'Current moderator membership is required';
  end if;
  perform public.approve_application_with_canonical_media(
    application_uuid, reviewer_uuid, expected_updated_at, note,
    avatar_descriptor, gallery_descriptors
  );
  perform private.append_privileged_audit(
    reviewer_uuid, 'application', application_uuid, 'approved_and_published',
    jsonb_build_object('after_status', 'approved')
  );
end;
$$;
revoke all on function public.approve_application_with_canonical_media_v2(uuid, uuid, timestamptz, text, jsonb, jsonb)
  from public, anon, authenticated;
grant execute on function public.approve_application_with_canonical_media_v2(uuid, uuid, timestamptz, text, jsonb, jsonb)
  to service_role;
revoke execute on function public.approve_application_with_canonical_media(uuid, uuid, timestamptz, text, jsonb, jsonb)
  from service_role;

create or replace function public.apply_specialist_revision_with_canonical_media_v2(
  revision_uuid uuid,
  reviewer_uuid uuid,
  expected_updated_at timestamptz,
  note text,
  avatar_descriptor jsonb,
  gallery_descriptors jsonb
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  if reviewer_uuid is null or not exists (
    select 1 from public.moderators where user_id = reviewer_uuid
  ) then
    raise exception using errcode = '42501', message = 'Current moderator membership is required';
  end if;
  perform public.apply_specialist_revision_with_canonical_media(
    revision_uuid, reviewer_uuid, expected_updated_at, note,
    avatar_descriptor, gallery_descriptors
  );
  perform private.append_privileged_audit(
    reviewer_uuid, 'specialist_revision', revision_uuid, 'approved',
    jsonb_build_object('after_status', 'approved', 'canonical_media', true)
  );
end;
$$;
revoke all on function public.apply_specialist_revision_with_canonical_media_v2(uuid, uuid, timestamptz, text, jsonb, jsonb)
  from public, anon, authenticated;
grant execute on function public.apply_specialist_revision_with_canonical_media_v2(uuid, uuid, timestamptz, text, jsonb, jsonb)
  to service_role;
revoke execute on function public.apply_specialist_revision_with_canonical_media(uuid, uuid, timestamptz, text, jsonb, jsonb)
  from service_role;

notify pgrst, 'reload schema';
commit;
